name: ReEdgeGPT Stable Python3.9

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 8 * * *"

permissions:
  contents: read

jobs:
  build_dev_version:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
    - name: Test Bot
      env:
        EDGE_COOKIES: ${{ secrets.EDGE_COOKIES }}
      run: python ./test/unit_test/test_bot.py