name: ReEdgeGPT Dev Python3.11

on:
  push:
    branches: [ "dev", "main"]
  schedule:
    - cron: "0 8 * * *"
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build_dev_version:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r dev_requirements.txt
    - name: Set UTF8
      run: |
        chcp 65001 #set code page to utf-8
        set PYTHONUTF8=1
    - name: Test Bot
      env:
        EDGE_COOKIES: ${{ secrets.EDGE_COOKIES }}
      run: python ./test/unit_test/test_bot/test_bot.py
    - name: Test Generation Image
      env:
        IMAGE_COOKIE: ${{ secrets.IMAGE_COOKIE }}
      run: python ./test/unit_test/test_generate_image/test_generation.py